    - name: Build Solution
      run: |
        msbuild revLoader/revLoader.vcxproj `
          /p:Configuration=$env:BUILD_CONFIGURATION `
          /p:Platform=Win32 `
          /p:VisualStudioVersion=15.0 `
          /verbosity:minimal
